name: Npm Publish

# 触发器
on:
  # 定时触发
  schedule:
    - cron: "00 02 * * *"
  # 手动触发 
  workflow_dispatch:

# 工作流
jobs:
  daily:
    # 运行系统
    runs-on: ubuntu-latest

    # 步骤
    steps:
      # 获取仓库
      - name: get repo
        uses: actions/checkout@v4.1.2
        with:
          token: ${{ secrets.ACTION_TOKEN }}

      # Node环境
      - name: Setup Node.js environment
        uses: actions/setup-node@v4.0.2
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/

      # 安装依赖
      - name: Install Dependencies
        run: npm install

      # 执行任务文件（脚本）
      - name: Run Main Task
        id: main
        run: npm run main

      # PrePublish 同上
      - name: PrePublish
        run: npm run prePublish

      # 提交Git
      - name: Github Push Action
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.ACTION_TOKEN }}

      # 提交NPM
      - name: Publish to NPM
        run: npm publish --access-publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOkEN }}
