name: Every 5 minutes

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  daily:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.2
        with:
          fetch-depth: 0
          ref: master

      # node 环境
      - uses: actions/setup-node@v4.0.2
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/

      # 安装依赖
      - name: Install Dependencies
        run: npm install
